apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  tls:
    - hosts:
      - app.35.231.26.204.nip.io
      - frontend.35.231.26.204.nip.io
      secretName: hello-app-tls
  ingressClassName: nginx
  rules:
  - host: "app.35.231.26.204.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app-service
            port:
              number: 80
  - host: "frontend.35.231.26.204.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: angular-inmueble-service
            port:
              number: 80



