apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    cert-manager.op/cluster-issuer: "letsencrypt-palabra-secreta"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "app.35.231.26.204.io"
    - "frontend.35.231.26.204.nip.io"
    secretName: secret-tls
  rules:
  - host: "app.35.231.26.204.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app-service
            port:
              number: 80
  - host: "frontend.35.231.26.204.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: angular-inmueble-service
            port:
              number: 80



