apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
  - host: "vaxidreztech.com"
    http:
      paths:
      - pathType: Prefix
        path: /frontend
        backend:
          service:
            name: app-service
            port:
              number: 80
  - host: "vaxidreztech.com"
    http:
      paths:
      - pathType: Prefix
        path: /backend
        backend:
          service:
            name: angular-inmueble-service
            port:
              number: 80



