apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
  - host: "app-34-69-91-215.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app-service
            port: 
              number: 80
  - host: "frontend-34-69-91-215.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: angular-inmueble-service
            port: 
              number: 80
